# Generated by Django 5.2.8 on 2026-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
